[env:esp32-s3-devkitc-1]
platform = espressif32
board    = esp32-s3-devkitc-1
framework = arduino

; —— 启用内置 PSRAM ——
board_build.psram = true
; 指定FLASH和PSRAM的运行模式
board_build.arduino.memory_type = qio_opi
; 编译选项（可选）
monitor_speed = 115200

build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCONFIG_TINYUSB_CDC_ENABLED=1
  -DUSB_VID=0x303A
  -DUSB_PID=0x1001

lib_deps =
  # RECOMMENDED
  # Accept new functionality in a backwards compatible manner and patches
  bodmer/TFT_eSPI @ ^2.5.43
  # RECOMMENDED
  # Accept new functionality in a backwards compatible manner and patches
  bodmer/TJpg_Decoder @ ^1.1.0
