[env:esp32-s3-devkitc-1]
platform = espressif32
board    = esp32-s3-devkitc-1
framework = arduino

; —— 启用 PSRAM 和 8MB Flash 分区 ——
board_build.psram = true
board_build.arduino.memory_type = qio_opi
board_build.flash_size = 8MB
board_build.partitions = partitions_8mb.csv

build_flags =
  -DBOARD_HAS_PSRAM
  -I$(PROJECT_DIR)/../../Users/29871/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32s3/include/esp-dl/include
  -L$(PROJECT_DIR)/../../Users/29871/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32s3/ld
  -lhuman_face_detect
  -ldl
  -lmfn

monitor_speed = 115200

lib_deps =
  bodmer/TFT_eSPI @ ^2.5.43
  bodmer/TJpg_Decoder @ ^1.1.0
